CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17
TARGETS = exo1 exo2 exo3 

all: $(TARGETS)

exo1: exo1.cpp
	$(CXX) $(CXXFLAGS) -o exo1 exo1.cpp

exo2: exo2.cpp
	$(CXX) $(CXXFLAGS) -o exo2 exo2.cpp

exo3: exo3.cpp
	$(CXX) $(CXXFLAGS) -o exo3 exo3.cpp

clean:
	rm -f $(TARGETS)
